### ISSUE TITLE
Unresolved specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by brainsik** [nandomoreirame/simplest#5]
I'm getting this off a fresh clone:

```
$ bundle install
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.8.3
Using thread_safe 0.3.5
Using addressable 2.4.0
Using sass 3.4.20
Using thor 0.19.1
Using colorator 0.1
Using colored 1.2
Using ffi 1.9.10
Using mercenary 0.3.5
Using mini_portile2 2.0.0
Using parallel 1.6.1
Using yell 2.0.5
Using rb-fsevent 0.9.7
Using kramdown 1.9.0
Using liquid 3.0.6
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using jekyll-paginate 1.1.0
Using posix-spawn 0.3.11
Using yajl-ruby 1.2.1
Using bundler 1.12.5
Using tzinfo 1.2.2
Using jekyll-sass-converter 1.4.0
Using bourbon 4.2.6
Using ethon 0.8.0
Using rb-inotify 0.9.5
Using nokogiri 1.6.7.1
Using pygments.rb 0.6.3
Using activesupport 4.2.5
Using typhoeus 0.8.0
Using listen 3.0.5
Using html-proofer 2.6.1
Using jekyll-watch 1.3.0
Using jekyll 3.0.1
Bundle complete! 6 Gemfile dependencies, 36 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ jekyll serve
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:35:in `block in setup': You have already activated sass 3.4.22, but your Gemfile requires sass 3.4.20. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `map'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:20:in `setup'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler.rb:95:in `setup'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/lib/jekyll/plugin_manager.rb:36:in `require_from_bundler'
    from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.1/exe/jekyll:9:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.1/bin/jekyll:23:in `load'
    from /usr/local/var/rbenv/versions/2.3.1/bin/jekyll:23:in `<main>'
```

Thanks!

**Comment by brainsik** [comment]
Gonna close this. Looks like it's a ruby thing where different gem versions are installed. I uninstalled all gems, gem installed bundler, and then bundle installed. Now I get past this.
